<?php
	echo "Mostrar la receta <br> Bla <br> Bla <br> Bla <br> Comentarios <br>";
	//Habria que cogerlos de la bd con una funcion del modelo, yo le arreo un array.
	$comentarios = [
    [
        'id' => 1,
        'id_receta' => 101,
        'id_usuario' => 1,
        'id_comentario_respuesta' => null,
        'texto' => 'Esta receta es increíble, muy fácil de seguir.',
        'fecha_creacion' => '2024-11-15',
        'valoracion' => 5,
    ],
    [
        'id' => 2,
        'id_receta' => 101,
        'id_usuario' => 2,
        'id_comentario_respuesta' => 1,
        'texto' => '¡Totalmente de acuerdo! La probé y quedó deliciosa.',
        'fecha_creacion' => '2024-11-16',
        'valoracion' => 5,
    ],
    [
        'id' => 3,
        'id_receta' => 102,
        'id_usuario' => 3,
        'id_comentario_respuesta' => null,
        'texto' => 'No me salió como esperaba, pero tal vez fue mi error.',
        'fecha_creacion' => '2024-11-10',
        'valoracion' => 3,
    ],
    [
        'id' => 4,
        'id_receta' => 103,
        'id_usuario' => 4,
        'id_comentario_respuesta' => null,
        'texto' => 'Gracias por compartir, muy útil.',
        'fecha_creacion' => '2024-11-11',
        'valoracion' => 4,
    ],
    [
        'id' => 5,
        'id_receta' => 104,
        'id_usuario' => 5,
        'id_comentario_respuesta' => null,
        'texto' => '¿Podrías sugerir un sustituto para la harina?',
        'fecha_creacion' => '2024-11-12',
        'valoracion' => null,
    ],
    [
        'id' => 6,
        'id_receta' => 104,
        'id_usuario' => 6,
        'id_comentario_respuesta' => 5,
        'texto' => 'Puedes usar harina de almendra, queda excelente.',
        'fecha_creacion' => '2024-11-13',
        'valoracion' => 5,
    ],
    [
        'id' => 7,
        'id_receta' => 105,
        'id_usuario' => 7,
        'id_comentario_respuesta' => null,
        'texto' => 'La preparación fue confusa, quizás más fotos ayudarían.',
        'fecha_creacion' => '2024-11-14',
        'valoracion' => 2,
    ],
    [
        'id' => 8,
        'id_receta' => 105,
        'id_usuario' => 8,
        'id_comentario_respuesta' => 7,
        'texto' => 'Estoy de acuerdo, me perdí en algunos pasos.',
        'fecha_creacion' => '2024-11-14',
        'valoracion' => 3,
    ],
    [
        'id' => 9,
        'id_receta' => 106,
        'id_usuario' => 9,
        'id_comentario_respuesta' => null,
        'texto' => 'Me encantó, perfecto para un día lluvioso.',
        'fecha_creacion' => '2024-11-10',
        'valoracion' => 5,
    ],
    [
        'id' => 10,
        'id_receta' => 107,
        'id_usuario' => 10,
        'id_comentario_respuesta' => null,
        'texto' => '¿Cuánto tiempo debo hornear si uso un molde más grande?',
        'fecha_creacion' => '2024-11-11',
        'valoracion' => null,
    ],
    [
        'id' => 11,
        'id_receta' => 108,
        'id_usuario' => 11,
        'id_comentario_respuesta' => null,
        'texto' => 'Hice esto para una reunión y a todos les encantó.',
        'fecha_creacion' => '2024-11-09',
        'valoracion' => 5,
    ],
    [
        'id' => 12,
        'id_receta' => 108,
        'id_usuario' => 12,
        'id_comentario_respuesta' => 11,
        'texto' => '¡Qué bien! También fue un éxito en mi casa.',
        'fecha_creacion' => '2024-11-10',
        'valoracion' => 5,
    ],
    [
        'id' => 13,
        'id_receta' => 109,
        'id_usuario' => 13,
        'id_comentario_respuesta' => null,
        'texto' => 'La receta está mal escrita, tuve que improvisar.',
        'fecha_creacion' => '2024-11-12',
        'valoracion' => 1,
    ],
    [
        'id' => 14,
        'id_receta' => 110,
        'id_usuario' => 14,
        'id_comentario_respuesta' => null,
        'texto' => '¡Un clásico! Nunca falla.',
        'fecha_creacion' => '2024-11-11',
        'valoracion' => 5,
    ],
    [
        'id' => 15,
        'id_receta' => 110,
        'id_usuario' => 15,
        'id_comentario_respuesta' => 14,
        'texto' => 'Totalmente de acuerdo, lo hago cada Navidad.',
        'fecha_creacion' => '2024-11-13',
        'valoracion' => 5,
    ],
    [
        'id' => 16,
        'id_receta' => 111,
        'id_usuario' => 16,
        'id_comentario_respuesta' => 15,
        'texto' => 'Muy buena receta, pero le agregué mi toque personal.',
        'fecha_creacion' => '2024-11-12',
        'valoracion' => 4,
    ],
    [
        'id' => 17,
        'id_receta' => 112,
        'id_usuario' => 17,
        'id_comentario_respuesta' => null,
        'texto' => 'Los ingredientes no eran claros, ¿pueden revisarlo?',
        'fecha_creacion' => '2024-11-10',
        'valoracion' => 2,
    ],
    [
        'id' => 18,
        'id_receta' => 113,
        'id_usuario' => 18,
        'id_comentario_respuesta' => null,
        'texto' => 'Perfecto, justo lo que buscaba.',
        'fecha_creacion' => '2024-11-15',
        'valoracion' => 5,
    ],
    [
        'id' => 19,
        'id_receta' => 114,
        'id_usuario' => 19,
        'id_comentario_respuesta' => null,
        'texto' => 'Le faltó algo de sabor, ¿alguna sugerencia?',
        'fecha_creacion' => '2024-11-16',
        'valoracion' => 3,
    ],
    [
        'id' => 20,
        'id_receta' => 114,
        'id_usuario' => 20,
        'id_comentario_respuesta' => 19,
        'texto' => 'Prueba con un poco más de sal y especias.',
        'fecha_creacion' => '2024-11-17',
        'valoracion' => 4,
    ],
];

	include "mostrarComentarios.php";
?>